% Prints out steady-state statistics
if adjtype<5, printstats_ssdp; break; end
% fprintf('\n')
% fprintf('Consumption                    : %0.3g \n',Cbar) 
% fprintf('Hours                          : %0.3g \n',Nbar)
% fprintf('Real money balances            : %0.3g \n',mbar)
% fprintf('Wage level                     : %0.3g \n',wbar)
% fprintf('Utility level                  : %0.4g \n',U)
fprintf('\n')
fprintf('Annual inflation               : %0.3g%% \n',100*(mu^12-1))     
fprintf('Frequency of price changes     : %0.3g%% \n',100*freqnonzeropchanges)
fprintf('Mean price change              : %0.3g \n',100*EPchange)     
fprintf('\n')
fprintf('Mean absolute price change     : %0.3g \n',100*MeanAbsPchange)
%fprintf('Median absolute price change   : %0.3g \n',100*MedAbsPchange)
fprintf('Std of price changes           : %0.3g \n',100*StdPchanges)  
fprintf('Kurtosis of price changes      : %0.3g \n',KurtPchanges)                                           
fprintf('\n')
fprintf('Mean price increase            : %0.3g \n',100*EPincrease)
%fprintf('Median price increase          : %0.3g \n',100*MedPincrease)
%fprintf('\n')
fprintf('Mean price decrease            : %0.3g \n',-100*EPdecrease)
%fprintf('Median price decrease          : %0.3g \n',-100*MedPdecrease)
%fprintf('\n')
fprintf('Fraction of price increases    : %0.3g%% \n',100*fracPriceIncr)
fprintf('Fraction of price changes <=5%% : %0.3g%% \n',100*fracSmallChanges)
fprintf('Fraction of price changes <=2.5%% : %0.3g%% \n',100*fracSmallChanges25)
%fprintf('\n')
%fprintf('Mean abs distance from p*     : %0.3g% \n',100*AvAbsDistFromPstar)
%fprintf('Median abs distance from p*   : %0.3g% \n',100*MedAbsPdistans)
fprintf('\n')
fprintf('Loss rel. to flex as %% revenue : %0.3g%% \n',100*loss2)
%fprintf('Max D as %% of median V         : %0.3g%% \n',100*maxD/MedV)
%fprintf('Min D as %% of median V         : %0.3g%% \n',100*minD/MedV)
% fprintf('\n')
% fprintf('Mean D as %% of median V        : %0.3g%% \n',100*MeanD/MedV)
% fprintf('Median D as %% of median V      : %0.3g%% \n',100*MedD/MedV)
% fprintf('\n')
% fprintf('Mean Dopt as %% of median V     : %0.3g%% \n',100*MeanDopt/MedV)
% fprintf('Median Dopt as %% of median V   : %0.3g%% \n',100*MedDopt/MedV)
% fprintf('\n')
% fprintf('Std of D as %% of median V      : %0.3g%% \n',100*StdD/MedV)
if adjtype==3                                                        
   fprintf('\n')
   fprintf('Menu cost as %% of revenue      : %0.3g%% \n',McostinRev)
   fprintf('Menu cost as %% of wage bill    : %0.3g%% \n',McostinWageBill)
   fprintf('Menu cost as %% of consumption  : %0.3g%% \n',McostinCbar)
end
fprintf('\n')
%fprintf('State dependence metric [0 1] : %0.3g \n',CalvoMenuMetric)

